spring.application.name=springAutenticacao
# Endereço do banco de dado
spring.datasource.url=jdbc:mysql://localhost:3306/api_auth
# Usuario que vc usa para entra no banco de dado
spring.datasource.username=root
# e asenha do seu usuario do banco de dado
spring.datasource.password=lauriana1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true